# https://github.com/sidekiq/sidekiq/wiki/Advanced-Options

# Sample configuration file for Sidekiq.
# Options here can still be overridden by cmd line args.
---
:verbose: true
:concurrency: 10
:timeout: 25

# Sidekiq will run this file through ERB when reading it so you can
# even put in dynamic logic, like a host-specific queue.
# http://www.mikeperham.com/2013/11/13/advanced-sidekiq-host-specific-queues/
:queues:
  - critical
  - high
  - default
  - low

# you can override concurrency based on environment
production:
  :concurrency: 25
staging:
  :concurrency: 15